# Generated by Django 3.2.9 on 2021-11-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211122_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='store.CartProduct', verbose_name='Продукты для корзины'),
        ),
    ]
