# Generated by Django 3.2.9 on 2021-11-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='url',
            new_name='slug',
        ),
    ]
